# vim:ft=yaml.docker-compose
version: "3"

networks:
  internal:
  proxy:
    name: "${NGINX_PROXY_NETWORK_NAME}"
    external: true

volumes:
  vpn_data:
  radarr_data:
  prowlarr_data:
  sonarr_data:
  overseerr_data:
  torrent_data:
  plex_data:
  tautulli_data:

services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:latest
    restart: always
    networks:
      - proxy
      - internal
    cap_add:
      - NET_ADMIN
    volumes:
      - vpn_data:/gluetun
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_VPN}"
      VIRTUAL_PATH: "${VIRTUAL_PATH_VPN}"
      VIRTUAL_DEST: /
      VIRTUAL_PORT: 8888
    env_file:
      - stack.env

  radarr:
    build:
      context: .
      dockerfile: ./radarr/Dockerfile
    restart: unless-stopped
    depends_on:
      - vpn
      - torrent
      - prowlarr
    networks:
      - proxy
      - internal
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_RADARR}"
      VIRTUAL_PATH: "${VIRTUAL_PATH_RADARR}"
      VIRTUAL_DEST: /
      VIRTUAL_PORT: 7878
    env_file:
      - stack.env
    volumes:
      - radarr_data:/config
      - ${MEDIA}:/data

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    networks:
      - proxy
      - internal
    depends_on:
      - vpn
      - torrent
    env_file:
      - stack.env
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_PROWLARR}"
      VIRTUAL_PATH: "${VIRTUAL_PATH_PROWLARR}"
      VIRTUAL_DEST: /
      VIRTUAL_PORT: 9696
    volumes:
      - prowlarr_data:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    networks:
      - proxy
      - internal
    depends_on:
      - vpn
      - torrent
      - prowlarr
    env_file:
      - stack.env
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_SONARR}"
      VIRTUAL_PATH: "${VIRTUAL_PATH_SONARR}"
      VIRTUAL_DEST: /
      VIRTUAL_PORT: 8989
    volumes:
      - sonarr_data:/config
      - ${MEDIA}:/data

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    networks:
      - proxy
      - internal
    depends_on:
      - vpn
      - sonarr
      - radarr
      - plex
      - tautulli
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_OVERSEERR}"
      VIRTUAL_PORT: 5055
    volumes:
      - overseerr_data:/config

  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: always
    networks:
      - proxy
      - internal
    depends_on:
      - vpn
    env_file:
      - stack.env
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_TORRENT}"
      VIRTUAL_PORT: 8080
    volumes:
      - torrent_data:/config
      - ${MEDIA}/downloads:/downloads
      - ${MEDIA}/torrents:/torrents

  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: always
    env_file:
      - stack.env
    networks:
      - proxy
      - internal
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_PLEX}"
      VIRTUAL_PATH: "${VIRTUAL_PATH_PLEX}"
      VIRTUAL_DEST: /
      VIRTUAL_PORT: 32400
    volumes:
      - plex_data:/config
      - ${MEDIA}/series:/tv
      - ${MEDIA}/movies:/movies

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    restart: always
    env_file:
      - stack.env
    networks:
      - proxy
      - internal
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST_TAUTULLI}"
      VIRTUAL_PATH: "${VIRTUAL_PATH_TAUTULLI}"
      VIRTUAL_DEST: /
      VIRTUAL_PORT: 32400
    volumes:
      - tautulli_data:/config
    ports:
      - 8181:8181
