# vim:ft=yaml.docker-compose
version: "3"

services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:latest
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888 # HTTP proxy
      - 8388:8388 # Shadowsocks
    volumes:
      - ${ROOT}/vpn:/gluetun
    env_file:
      - stack.env

  radarr:
    build:
      context: .
      dockerfile: ./radarr/Dockerfile
    restart: unless-stopped
    depends_on:
      - vpn
      - torrent
      - prowlarr
    env_file:
      - stack.env
    ports:
      - 7878:7878
    volumes:
      - ${ROOT}/radarr:/config
      - ${MEDIA}:/data

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    depends_on:
      - vpn
      - torrent
    env_file:
      - stack.env
    ports:
      - 9696:9696
    volumes:
      - ${ROOT}/prowlarr:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    depends_on:
      - vpn
      - torrent
      - prowlarr
    env_file:
      - stack.env
    ports:
      - 8989:8989
    volumes:
      - ${ROOT}/sonarr:/config
      - ${MEDIA}:/data

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    depends_on:
      - vpn
      - sonarr
      - radarr
      - plex
      - tautulli
    ports:
      - 5055:5055
    volumes:
      - ${ROOT}/overseerr:/config

  torrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    restart: always
    depends_on:
      - vpn
    ports:
      - 8080:8080
    env_file:
      - stack.env
    volumes:
      - ${ROOT}/torrent:/config
      - ${MEDIA}/downloads:/downloads
      - ${MEDIA}/torrents:/torrents

  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: always
    network_mode: 'host'
    env_file:
      - stack.env
    volumes:
      - ${ROOT}/plex:/config
      - ${MEDIA}/series:/tv
      - ${MEDIA}/movies:/movies

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    restart: always
    env_file:
      - stack.env
    volumes:
      - ${ROOT}/tautulli:/config
    ports:
      - 8181:8181
