FROM lscr.io/linuxserver/radarr:latest
ADD https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/radarr/scripts_init.bash /custom-cont-init.d/scripts_init.bash
RUN bash /custom-cont-init.d/scripts_init.bash
